name: Scheduled Health Check

on:
  schedule:
    - cron: "*/30 * * * *"  
  workflow_dispatch:       
  push:                     

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    
      
      - name: Setup Git Config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Make health-check.sh executable
        run: chmod +x ./health-check.sh
      
      - name: Run Health Check Script
        run: ./health-check.sh
      
      - name: Commit and Push Changes
        run: |
          git add -A --force logs/
          git commit -m "[Automated] Update Health Check Logs" || echo "No changes to commit"
          git push